#!/bin/bash

#!@brief abort when user error
# @args message
die_user() {
    echo $1 > /dev/stderr
    exit 1
}
#!@brief abort when implementation error
# @args message
die_impl() {
    echo $1 > /dev/stderr
    exit 2
}
#!@brief check if a command is installed
# @args command package-name
# @notice If package-name is omitted, command is used as the package-name
check_cmd() {
    if (($# < 2)); then
        package_name=$1
    else
        package_name=$2
    fi
    which $1 > /dev/null 2>&1 || die_user "$package_name is not installed!"
}

## Main Procedure
(($# < 2)) && die_user "usage: $0 command server-name"

cmd=$1
server_name=$2
conf_file=~/.vmctl.json
server_type=$(jq -r --arg name $server_name '.[] | if (.name == $name) then .type else empty end' $conf_file)

# check if the server exists
[[ -z $server_type ]] && die_user "Server $server_name is not found!"

## dependency check
check_cmd jq
case $server_type in
    ec2)
        check_cmd aws aws-cli
        ;;
    virtual_box)
        check_cmd VBoxManage VirtualBox
        ;;
esac

# extract the config of the operated server
jq -r --arg name $server_name '.[] | if (.name == $name) then . else empty end' $conf_file |
    case $server_type in
        ec2)
            jq -r '.instance_id,.profile' | xargs | awk 'NF>1{$3=$2;$2="--profile"}$1;' |
                case $cmd in
                    start)
                        xargs aws ec2 start-instances --instance-ids
                        ;;
                    stop)
                        xargs aws ec2 stop-instances --instance-ids
                        ;;
                    restart)
                        xargs aws ec2 reboot-instances --instance-ids
                        ;;
                    save)
                        echo 'EC2 insatance cannot be saved!'
                        ;;
                    status)
                        die_impl "Unimplemented command: $cmd for ec2"
                        ;;
                    *)
                        die_user "Unsupported command: $cmd for ec2"
                esac
            ;;
        virtual_box)
            jq -r '.instance_id' |
                case $cmd in
                    start)
                        xargs -I{} VBoxManage startvm {} --type headless
                        ;;
                    stop)
                        xargs -I{} VBoxManage controlvm {} poweroff
                        ;;
                    restart)
                        xargs -I{} VBoxManage controlvm {} reset
                        ;;
                    save)
                        xargs -I{} VBoxManage controlvm {} savestate
                        ;;
                    status)
                        die_impl "Unimplemented command: $cmd for virtual_box"
                        ;;
                    *)
                        die_user "Unsupported command: $cmd for virtual_box"
                esac
            ;;
        *)
            die_user "Unsupported server type: $server_type"
    esac
